[package]
name = "allows_tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
allows = { path = "../allows", version = "0.1.*" }

[dev-dependencies]
# ui_test = "0.8.*"
