[package]
name = "allows"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.*.*"
allows_internals = { path = "../../allows_internals", version = "0.1.*" }