//! `clippy` lint macros, re-exported from [`allow_prefixed`](../allow_prefixed) crate.

// MAINTAINERS: See rustc.rs

// Based on https://rust-lang.github.io/rust-clippy/index.html for 1.45 to master:
//
// Any clippy:: lint marked as `rustversion::since(1.44.1)` may have existed earlier, too.

#[rustversion::since(1.45)]
#[rustfmt::skip]
pub use allow_prefixed::{
    clippy_absurd_extreme_comparisons as absurd_extreme_comparisons,
    clippy_almost_swapped as almost_swapped,
    clippy_approx_constant as approx_constant,
    clippy_as_conversions as as_conversions,
    clippy_assertions_on_constants as assertions_on_constants,
    clippy_assign_op_pattern as assign_op_pattern,
    // clippy::assign_ops is deprecated since at least 1.45
    clippy_await_holding_lock as await_holding_lock,
    clippy_bad_bit_mask as bad_bit_mask,
    clippy_bind_instead_of_map as bind_instead_of_map,
    // clippy::blacklisted_name has been renamed to `clippy::disallowed_names`
    clippy_blocks_in_if_conditions as blocks_in_if_conditions,
    clippy_bool_comparison as bool_comparison,
    clippy_borrow_interior_mutable_const as borrow_interior_mutable_const,
    clippy_borrowed_box as borrowed_box,
    clippy_boxed_local as boxed_local,
    clippy_builtin_type_shadow as builtin_type_shadow,
    clippy_cargo_common_metadata as cargo_common_metadata,
    clippy_cast_lossless as cast_lossless,
    clippy_cast_possible_truncation as cast_possible_truncation,
    clippy_cast_possible_wrap as cast_possible_wrap,
    clippy_cast_precision_loss as cast_precision_loss,
    clippy_cast_ptr_alignment as cast_ptr_alignment,
    clippy_cast_ref_to_mut as cast_ref_to_mut,
    clippy_cast_sign_loss as cast_sign_loss,
    clippy_char_lit_as_u8 as char_lit_as_u8,
    clippy_chars_last_cmp as chars_last_cmp,
    clippy_chars_next_cmp as chars_next_cmp,
    clippy_checked_conversions as checked_conversions,
    clippy_clone_double_ref as clone_double_ref,
    clippy_clone_on_copy as clone_on_copy,
    clippy_clone_on_ref_ptr as clone_on_ref_ptr,
    clippy_cmp_nan as cmp_nan,
    clippy_cmp_null as cmp_null,
    clippy_cmp_owned as cmp_owned,
    clippy_cognitive_complexity as cognitive_complexity,
    clippy_collapsible_if as collapsible_if,
    clippy_comparison_chain as comparison_chain,
    clippy_copy_iterator as copy_iterator,
    clippy_crosspointer_transmute as crosspointer_transmute,
    clippy_dbg_macro as dbg_macro,
    clippy_debug_assert_with_mut_call as debug_assert_with_mut_call,
    clippy_decimal_literal_representation as decimal_literal_representation,
    clippy_declare_interior_mutable_const as declare_interior_mutable_const,
    clippy_default_trait_access as default_trait_access,
    clippy_deprecated_cfg_attr as deprecated_cfg_attr,
    clippy_deprecated_semver as deprecated_semver,
    clippy_deref_addrof as deref_addrof,
    // clippy::derive_hash_xor_eq has been renamed to `clippy::derived_hash_with_manual_eq`
    clippy_diverging_sub_expression as diverging_sub_expression,
    clippy_doc_markdown as doc_markdown,
    clippy_double_comparisons as double_comparisons,
    clippy_double_must_use as double_must_use,
    clippy_double_neg as double_neg,
    clippy_double_parens as double_parens,
    clippy_drop_copy as drop_copy,
    clippy_drop_ref as drop_ref,
    clippy_duplicate_underscore_argument as duplicate_underscore_argument,
    clippy_duration_subsec as duration_subsec,
    clippy_else_if_without_else as else_if_without_else,
    clippy_empty_enum as empty_enum,
    clippy_empty_line_after_outer_attr as empty_line_after_outer_attr,
    clippy_empty_loop as empty_loop,
    clippy_enum_clike_unportable_variant as enum_clike_unportable_variant,
    clippy_enum_glob_use as enum_glob_use,
    clippy_enum_variant_names as enum_variant_names,
    clippy_eq_op as eq_op,
    clippy_erasing_op as erasing_op,
    // clippy::eval_order_dependence has been renamed to `clippy::mixed_read_write_in_expression`
    clippy_excessive_precision as excessive_precision,
    clippy_exit as exit,
    clippy_expect_fun_call as expect_fun_call,
    clippy_expect_used as expect_used,
    clippy_expl_impl_clone_on_copy as expl_impl_clone_on_copy,
    clippy_explicit_counter_loop as explicit_counter_loop,
    clippy_explicit_deref_methods as explicit_deref_methods,
    clippy_explicit_into_iter_loop as explicit_into_iter_loop,
    clippy_explicit_iter_loop as explicit_iter_loop,
    clippy_explicit_write as explicit_write,
    // clippy::extend_from_slice is deprecated since at least 1.44.1
    clippy_extra_unused_lifetimes as extra_unused_lifetimes,
    clippy_fallible_impl_from as fallible_impl_from,
    clippy_filetype_is_file as filetype_is_file,
    // clippy::filter_map has been removed: this lint has been replaced by `manual_filter_map`, a
    // more specific (and prefixless) lint.
    clippy_filter_map_next as filter_map_next,
    clippy_filter_next as filter_next,
    // clippy::find_map has been removed: this lint has been replaced by `manual_find_map`, a more
    // specific (and prefixless) lint.
    clippy_flat_map_identity as flat_map_identity,
    clippy_float_arithmetic as float_arithmetic,
    clippy_float_cmp as float_cmp,
    clippy_float_cmp_const as float_cmp_const,
    clippy_fn_address_comparisons as fn_address_comparisons,
    clippy_fn_params_excessive_bools as fn_params_excessive_bools,
    clippy_fn_to_numeric_cast as fn_to_numeric_cast,
    clippy_fn_to_numeric_cast_with_truncation as fn_to_numeric_cast_with_truncation,
    clippy_for_kv_map as for_kv_map,
    // for_loop_over_option is removed since 1.45
    //
    // for_loop_over_result is removed since 1.45
    //
    // clippy::for_loops_over_fallibles has been renamed to (prefixless) `for_loops_over_fallibles`
    clippy_forget_copy as forget_copy,
    clippy_forget_ref as forget_ref,
    clippy_future_not_send as future_not_send,
    clippy_get_last_with_len as get_last_with_len,
    clippy_get_unwrap as get_unwrap,
    clippy_identity_op as identity_op,
    clippy_if_let_mutex as if_let_mutex,
    // clippy::if_let_redundant_pattern_matching is deprecated since at least 1.45
    //
    // clippy::if_let_some_result has been renamed to `clippy::match_result_ok`
    clippy_if_not_else as if_not_else,
    clippy_if_same_then_else as if_same_then_else,
    clippy_ifs_same_cond as ifs_same_cond,
    clippy_implicit_hasher as implicit_hasher,
    clippy_implicit_return as implicit_return,
    clippy_implicit_saturating_sub as implicit_saturating_sub,
    clippy_imprecise_flops as imprecise_flops,
    clippy_inconsistent_digit_grouping as inconsistent_digit_grouping,
    clippy_indexing_slicing as indexing_slicing,
    clippy_ineffective_bit_mask as ineffective_bit_mask,
    clippy_inefficient_to_string as inefficient_to_string,
    clippy_infallible_destructuring_match as infallible_destructuring_match,
    clippy_infinite_iter as infinite_iter,
    clippy_inherent_to_string as inherent_to_string,
    clippy_inherent_to_string_shadow_display as inherent_to_string_shadow_display,
    clippy_inline_always as inline_always,
    clippy_inline_fn_without_body as inline_fn_without_body,
    clippy_int_plus_one as int_plus_one,
    clippy_integer_arithmetic as integer_arithmetic,
    clippy_integer_division as integer_division,
    // clippy::into_iter_on_array is deprecated since at least 1.45
    clippy_into_iter_on_ref as into_iter_on_ref,
    // clippy::invalid_atomic_ordering has been renamed to (prefixless) `invalid_atomic_ordering`
    //
    // clippy::invalid_ref is deprecated since at least 1.44.1
    clippy_invalid_regex as invalid_regex,
    clippy_invalid_upcast_comparisons as invalid_upcast_comparisons,
    clippy_invisible_characters as invisible_characters,
    clippy_items_after_statements as items_after_statements,
    clippy_iter_cloned_collect as iter_cloned_collect,
    clippy_iter_next_loop as iter_next_loop,
    clippy_iter_nth as iter_nth,
    clippy_iter_nth_zero as iter_nth_zero,
    clippy_iter_skip_next as iter_skip_next,
    clippy_iterator_step_by_zero as iterator_step_by_zero,
    clippy_just_underscores_and_digits as just_underscores_and_digits,
    clippy_large_const_arrays as large_const_arrays,
    clippy_large_enum_variant as large_enum_variant,
    clippy_large_stack_arrays as large_stack_arrays,
    clippy_len_without_is_empty as len_without_is_empty,
    clippy_len_zero as len_zero,
    clippy_let_and_return as let_and_return,
    clippy_let_underscore_lock as let_underscore_lock,
    clippy_let_underscore_must_use as let_underscore_must_use,
    clippy_let_unit_value as let_unit_value,
    clippy_linkedlist as linkedlist,
    // clippy::logic_bug has been renamed to `clippy::overly_complex_bool_expr`
    clippy_lossy_float_literal as lossy_float_literal,
    clippy_macro_use_imports as macro_use_imports,
    clippy_main_recursion as main_recursion,
    clippy_manual_async_fn as manual_async_fn,
    clippy_manual_memcpy as manual_memcpy,
    clippy_manual_non_exhaustive as manual_non_exhaustive,
    clippy_manual_saturating_arithmetic as manual_saturating_arithmetic,
    clippy_manual_swap as manual_swap,
    clippy_many_single_char_names as many_single_char_names,
    clippy_map_clone as map_clone,
    clippy_map_entry as map_entry,
    clippy_map_flatten as map_flatten,
    clippy_map_unwrap_or as map_unwrap_or,
    clippy_match_as_ref as match_as_ref,
    clippy_match_bool as match_bool,
    clippy_match_on_vec_items as match_on_vec_items,
    clippy_match_overlapping_arm as match_overlapping_arm,
    clippy_match_ref_pats as match_ref_pats,
    clippy_match_same_arms as match_same_arms,
    clippy_match_single_binding as match_single_binding,
    clippy_match_wild_err_arm as match_wild_err_arm,
    clippy_match_wildcard_for_single_variants as match_wildcard_for_single_variants,
    clippy_maybe_infinite_iter as maybe_infinite_iter,
    // clippy::mem_discriminant_non_enum has been renamed to (prefixless) `enum_intrinsics_non_enums`
    clippy_mem_forget as mem_forget,
    clippy_mem_replace_option_with_none as mem_replace_option_with_none,
    clippy_mem_replace_with_default as mem_replace_with_default,
    clippy_mem_replace_with_uninit as mem_replace_with_uninit,
    clippy_min_max as min_max,
    // clippy::misaligned_transmute is deprecated since at least 1.44.1
    clippy_mismatched_target_os as mismatched_target_os,
    clippy_misrefactored_assign_op as misrefactored_assign_op,
    clippy_missing_const_for_fn as missing_const_for_fn,
    clippy_missing_docs_in_private_items as missing_docs_in_private_items,
    clippy_missing_errors_doc as missing_errors_doc,
    clippy_missing_inline_in_public_items as missing_inline_in_public_items,
    clippy_missing_safety_doc as missing_safety_doc,
    clippy_mistyped_literal_suffixes as mistyped_literal_suffixes,
    clippy_mixed_case_hex_literals as mixed_case_hex_literals,
    clippy_module_inception as module_inception,
    clippy_module_name_repetitions as module_name_repetitions,
    clippy_modulo_arithmetic as modulo_arithmetic,
    clippy_modulo_one as modulo_one,
    clippy_multiple_crate_versions as multiple_crate_versions,
    clippy_multiple_inherent_impl as multiple_inherent_impl,
    clippy_must_use_candidate as must_use_candidate,
    clippy_must_use_unit as must_use_unit,
    clippy_mut_from_ref as mut_from_ref,
    clippy_mut_mut as mut_mut,
    clippy_mut_range_bound as mut_range_bound,
    clippy_mutable_key_type as mutable_key_type,
    clippy_mutex_atomic as mutex_atomic,
    clippy_mutex_integer as mutex_integer,
    clippy_naive_bytecount as naive_bytecount,
    clippy_needless_bool as needless_bool,
    clippy_needless_borrow as needless_borrow,
    clippy_needless_borrowed_reference as needless_borrowed_reference,
    clippy_needless_collect as needless_collect,
    clippy_needless_continue as needless_continue,
    clippy_needless_doctest_main as needless_doctest_main,
    clippy_needless_lifetimes as needless_lifetimes,
    clippy_needless_pass_by_value as needless_pass_by_value,
    clippy_needless_range_loop as needless_range_loop,
    clippy_needless_return as needless_return,
    clippy_needless_update as needless_update,
    clippy_neg_cmp_op_on_partial_ord as neg_cmp_op_on_partial_ord,
    clippy_neg_multiply as neg_multiply,
    clippy_never_loop as never_loop,
    clippy_new_ret_no_self as new_ret_no_self,
    clippy_new_without_default as new_without_default,
    clippy_no_effect as no_effect,
    clippy_non_ascii_literal as non_ascii_literal,
    clippy_nonminimal_bool as nonminimal_bool,
    clippy_nonsensical_open_options as nonsensical_open_options,
    clippy_not_unsafe_ptr_arg_deref as not_unsafe_ptr_arg_deref,
    clippy_ok_expect as ok_expect,
    clippy_op_ref as op_ref,
    clippy_option_as_ref_deref as option_as_ref_deref,
    clippy_option_env_unwrap as option_env_unwrap,
    clippy_option_map_or_none as option_map_or_none,
    clippy_option_map_unit_fn as option_map_unit_fn,
    // option_map_unwrap_or is removed since 1.45.0 TODO check
    //
    // option_mapw_unwrap_or_else is removed since 1.45.0 TODO check
    clippy_option_option as option_option,
    // option_unwrap_used is removed since 1.45.0 TODO check
    clippy_or_fun_call as or_fun_call,
    clippy_out_of_bounds_indexing as out_of_bounds_indexing,
    clippy_overflow_check_conditional as overflow_check_conditional,
    clippy_panic as panic,
    // clippy::panic_params has been renamed to (prefixless)
    clippy_panicking_unwrap as panicking_unwrap,
    clippy_partialeq_ne_impl as partialeq_ne_impl,
    clippy_path_buf_push_overwrite as path_buf_push_overwrite,
    clippy_possible_missing_comma as possible_missing_comma,
    clippy_precedence as precedence,
    clippy_print_literal as print_literal,
    clippy_print_stdout as print_stdout,
    clippy_print_with_newline as print_with_newline,
    clippy_println_empty_string as println_empty_string,
    clippy_ptr_arg as ptr_arg,
    clippy_ptr_offset_with_cast as ptr_offset_with_cast,
    // clippy::pub_enum_variant_names has been removed. set the `avoid-breaking-exported-api` config
    // option to `false` to enable the `enum_variant_names` lint for public items. (Probably a
    // prefixless lint; `allow_prefixed` and `allow` crates don't support attribute parameters.)
    clippy_question_mark as question_mark,
    clippy_range_minus_one as range_minus_one,
    clippy_range_plus_one as range_plus_one,
    // clippy::range_step_by_zero is deprecated since at least 1.44.1
    clippy_range_zip_with_len as range_zip_with_len,
    clippy_redundant_allocation as redundant_allocation,
    clippy_redundant_clone as redundant_clone,
    clippy_redundant_closure as redundant_closure,
    clippy_redundant_closure_call as redundant_closure_call,
    clippy_redundant_closure_for_method_calls as redundant_closure_for_method_calls,
    clippy_redundant_field_names as redundant_field_names,
    clippy_redundant_pattern as redundant_pattern,
    clippy_redundant_pattern_matching as redundant_pattern_matching,
    clippy_redundant_pub_crate as redundant_pub_crate,
    clippy_redundant_static_lifetimes as redundant_static_lifetimes,
    // clippy::ref_in_deref has been renamed to clippy::needless_borrow
    //
    // clippy::regex_macro has been removed
    //
    // clippy::replace_consts is deprecated since 1.45
    clippy_rest_pat_in_fully_bound_structs as rest_pat_in_fully_bound_structs,
    // result_expect_used has been removed since 1.45 TODO check
    clippy_result_map_or_into_option as result_map_or_into_option,
    clippy_result_map_unit_fn as result_map_unit_fn,
    // result_map_unwrap_or_else is removed since 1.45 TODO check
    //
    // result_unwrap_used is removed since 1.45 TODO check
    //
    // reverse_range_loop is removed since 1.45 TODO check
    clippy_reversed_empty_ranges as reversed_empty_ranges,
    clippy_same_functions_in_if_condition as same_functions_in_if_condition,
    clippy_search_is_some as search_is_some,
    clippy_serde_api_misuse as serde_api_misuse,
    clippy_shadow_reuse as shadow_reuse,
    clippy_shadow_same as shadow_same,
    clippy_shadow_unrelated as shadow_unrelated,
    clippy_short_circuit_statement as short_circuit_statement,
    // clippy::should_assert_eq is deprecated since at least 1.44.1
    clippy_should_implement_trait as should_implement_trait,
    clippy_similar_names as similar_names,
    clippy_single_char_pattern as single_char_pattern,
    clippy_single_component_path_imports as single_component_path_imports,
    clippy_single_match as single_match,
    clippy_single_match_else as single_match_else,
    clippy_skip_while_next as skip_while_next,
    clippy_slow_vector_initialization as slow_vector_initialization,
    // clippy::str_to_string is deprecated since at least 1.44.1
    clippy_string_add as string_add,
    clippy_string_add_assign as string_add_assign,
    clippy_string_extend_chars as string_extend_chars,
    clippy_string_lit_as_bytes as string_lit_as_bytes,
    // clippy::string_to_string is deprecated since at least 1.44.1
    clippy_struct_excessive_bools as struct_excessive_bools,
    clippy_suboptimal_flops as suboptimal_flops,
    clippy_suspicious_arithmetic_impl as suspicious_arithmetic_impl,
    clippy_suspicious_assignment_formatting as suspicious_assignment_formatting,
    clippy_suspicious_else_formatting as suspicious_else_formatting,
    clippy_suspicious_map as suspicious_map,
    clippy_suspicious_op_assign_impl as suspicious_op_assign_impl,
    clippy_suspicious_unary_op_formatting as suspicious_unary_op_formatting,
    clippy_tabs_in_doc_comments as tabs_in_doc_comments,
    clippy_temporary_assignment as temporary_assignment,
    // clippy::temporary_cstring_as_ptr is renamed to (prefixless) temporary_cstring_as_ptr
    clippy_to_digit_is_some as to_digit_is_some,
    clippy_todo as todo,
    clippy_too_many_arguments as too_many_arguments,
    clippy_too_many_lines as too_many_lines,
    clippy_toplevel_ref_arg as toplevel_ref_arg,
    clippy_transmute_bytes_to_str as transmute_bytes_to_str,
    clippy_transmute_float_to_int as transmute_float_to_int,
    clippy_transmute_int_to_bool as transmute_int_to_bool,
    clippy_transmute_int_to_char as transmute_int_to_char,
    clippy_transmute_int_to_float as transmute_int_to_float,
    clippy_transmute_ptr_to_ptr as transmute_ptr_to_ptr,
    clippy_transmute_ptr_to_ref as transmute_ptr_to_ref,
    clippy_transmuting_null as transmuting_null,
    clippy_trivial_regex as trivial_regex,
    clippy_trivially_copy_pass_by_ref as trivially_copy_pass_by_ref,
    clippy_try_err as try_err,
    clippy_type_complexity as type_complexity,
    clippy_type_repetition_in_bounds as type_repetition_in_bounds,
    clippy_unicode_not_nfc as unicode_not_nfc,
    clippy_unimplemented as unimplemented,
    clippy_uninit_assumed_init as uninit_assumed_init,
    clippy_unit_arg as unit_arg,
    clippy_unit_cmp as unit_cmp,
    // clippy::unknown_clippy_lints is renamed to (prefixless rustc lint) unknown_lints
    clippy_unnecessary_cast as unnecessary_cast,
    clippy_unnecessary_filter_map as unnecessary_filter_map,
    clippy_unnecessary_fold as unnecessary_fold,
    clippy_unnecessary_mut_passed as unnecessary_mut_passed,
    clippy_unnecessary_operation as unnecessary_operation,
    clippy_unnecessary_unwrap as unnecessary_unwrap,
    clippy_unneeded_field_pattern as unneeded_field_pattern,
    clippy_unneeded_wildcard_pattern as unneeded_wildcard_pattern,
    clippy_unreachable as unreachable,
    clippy_unreadable_literal as unreadable_literal,
    clippy_unsafe_derive_deserialize as unsafe_derive_deserialize,
    clippy_unsafe_removed_from_name as unsafe_removed_from_name,
    // clippy::unsafe_vector_initialization is deprecated since at least 1.44.1
    clippy_unseparated_literal_suffix as unseparated_literal_suffix,
    clippy_unsound_collection_transmute as unsound_collection_transmute,
    // clippy::unstable_as_mut_slice is deprecated since at least 1.44.1
    //
    // clippy::unstable_as_slice is deprecated since at least 1.44.1
    //
    // clippy::unused_collect is deprecated since at least 1.44.1
    clippy_unused_io_amount as unused_io_amount,
    clippy_unused_self as unused_self,
    clippy_unused_unit as unused_unit,
    clippy_unwrap_used as unwrap_used,
    clippy_use_debug as use_debug,
    clippy_use_self as use_self,
    clippy_used_underscore_binding as used_underscore_binding,
    clippy_useless_asref as useless_asref,
    clippy_useless_attribute as useless_attribute,
    clippy_useless_conversion as useless_conversion,
    clippy_useless_format as useless_format,
    clippy_useless_let_if_seq as useless_let_if_seq,
    clippy_useless_transmute as useless_transmute,
    clippy_useless_vec as useless_vec,
    clippy_vec_box as vec_box,
    clippy_verbose_bit_mask as verbose_bit_mask,
    clippy_verbose_file_reads as verbose_file_reads,
    clippy_vtable_address_comparisons as vtable_address_comparisons,
    clippy_while_immutable_condition as while_immutable_condition,
    clippy_while_let_loop as while_let_loop,
    clippy_while_let_on_iterator as while_let_on_iterator,
    clippy_wildcard_dependencies as wildcard_dependencies,
    clippy_wildcard_enum_match_arm as wildcard_enum_match_arm,
    clippy_wildcard_imports as wildcard_imports,
    clippy_wildcard_in_or_patterns as wildcard_in_or_patterns,
    clippy_write_literal as write_literal,
    clippy_write_with_newline as write_with_newline,
    // clippy::writeln_empty_string is removed: set the `avoid-breaking-exported-api` config option
    // to `false` to enable the `wrong_self_convention` lint for public items. (Probably a
    // prefixless lint; `allow_prefixed` and `allow` crates don't support attribute parameters.)
    //
    // clippy::wrong_pub_self_convention has been removed: set the `avoid-breaking-exported-api`
    // config option to `false` to enable the `wrong_self_convention` lint for public items.
    // (Probably a prefixless lint; `allow_prefixed` and `allow` crates don't support attribute
    // parameters.)
    clippy_wrong_self_convention as wrong_self_convention,
    clippy_wrong_transmute as wrong_transmute,
    clippy_zero_divided_by_zero as zero_divided_by_zero,
    clippy_zero_prefixed_literal as zero_prefixed_literal,
    clippy_zero_ptr as zero_ptr,
    // clippy::zero_width_space renamed in 1.49 to clippy::invisible_characters
    clippy_zst_offset as zst_offset,
};
