[package]
name = "allow"
version = "0.1.0"
edition = "2021"
# NO rust-version here, because that applies only from 1.56. Based on
# https://github.com/dtolnay/rustversion it seems that we support 1.31+.

[lib]
proc-macro = true
test = true     # we have unit tests
doctest = false # but no doc tests


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustversion = "1.0"
allow_internal = { path = "../allow_internal", version = "0.1.*" }

[build-dependencies]
rustversion = "1.0"

[dev-dependencies]
ui_test = "0.8.*"
colored = "2"

[[test]]
name = "internal_checks"
harness = false
